{% set version = "3.3.5" %}

package:
  name: cfunits
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfunits/cfunits-{{ version }}.tar.gz
  sha256: dd53b2e5d04d5188b88aac413fed267271432d60347ebe0b48298d405a930bf0
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cftime >=1.5.0
    - numpy >=1.15
    - udunits2

test:
  imports:
    - cfunits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python interface to UNIDATA's Udunits-2 package with CF extensions

  description: |
    A python interface to UNIDATA`s Udunits-2 library with CF extensions.
    Store, combine and compare physical units and convert numeric values to different units.
    Units are as defined in UNIDATA`s Udunits-2 library <http://www.unidata.ucar.edu/software/udunits/>,
    except for reference time units (such as 'days since 2000-12-1' in the 'proleptic_gregorian' calendar),
    which are handled by the netCDF4 python package.
    In addition, some units are either new to, modified from, or removed from the standard
    Udunits-2 database in order to be more consistent with the CF conventions <http://cfconventions.org/>.
  doc_url: http://pythonhosted.org/cfunits/
  dev_url: https://bitbucket.org/cfpython/cfunits-python/

extra:
  recipe-maintainers:
    - cehbrecht
    - ocefpaf
