{% set version = "3.2.6" %}

package:
  name: cfunits
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfunits/cfunits-{{ version }}.tar.gz
  sha256: 3fdbb0473f972a19ff3dd36d6d1302733f03a1ad9e0e86e421f58116c2b1ae28
build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cftime >=1.1.1
    - numpy >=1.15
    - udunits2

test:
  imports:
    - cfunits

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A python interface to UNIDATA's Udunits-2 package with CF extensions"

  description: |
    A python interface to UNIDATA`s Udunits-2 library with CF extensions.
    Store, combine and compare physical units and convert numeric values to different units.
    Units are as defined in UNIDATA`s Udunits-2 library <http://www.unidata.ucar.edu/software/udunits/>,
    except for reference time units (such as 'days since 2000-12-1' in the 'proleptic_gregorian' calendar),
    which are handled by the netCDF4 python package.
    In addition, some units are either new to, modified from, or removed from the standard
    Udunits-2 database in order to be more consistent with the CF conventions <http://cfconventions.org/>.
  doc_url: http://pythonhosted.org/cfunits/
  dev_url: https://bitbucket.org/cfpython/cfunits-python/

extra:
  recipe-maintainers:
    - cehbrecht
    - ocefpaf
