{% set version = "1.9" %}

package:
  name: cfunits
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfunits/cfunits-{{ version }}.tar.gz
  sha256: f93817f9d6dd4ef38506d04bbd3f32901516e41e545754fd8b550f8db9cae7fd
  patches:
  - windll.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - netcdf4
    - numpy
    - udunits2

test:
  imports:
    - cfunits

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'A python interface to UNIDATA`s Udunits-2 package with CF extensions'

  description: |
    A python interface to UNIDATA`s Udunits-2 library with CF extensions.
    Store, combine and compare physical units and convert numeric values to different units.
    Units are as defined in UNIDATA`s Udunits-2 library <http://www.unidata.ucar.edu/software/udunits/>,
    except for reference time units (such as 'days since 2000-12-1' in the 'proleptic_gregorian' calendar),
    which are handled by the netCDF4 python package.
    In addition, some units are either new to, modified from, or removed from the standard
    Udunits-2 database in order to be more consistent with the CF conventions <http://cfconventions.org/>.
  doc_url: http://pythonhosted.org/cfunits/
  dev_url: https://bitbucket.org/cfpython/cfunits-python/

extra:
  recipe-maintainers:
    - cehbrecht
