appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: yzB2WDzoZnrydbdhkXJqUN4CSTcl4KgMHXDhC/FT91fFw4lBqN8Q6318PEpUz5y5FHvDXCgLkcipq6lIrCUsL3eU1AfsIYBm1RX0bSrMEC+TYFeBhAEwcGP3jCQ5y/oLWtBDCbtCTPYZaL8lm2/2jkQGgXT2IOM9jND29nBheJ5Fe4LiVTRkvzyKZLrY9KRNS0ehh1DWPocBwxs1EB7J5vxQsFHslBQWOwycqBS22bGre50/Q9BpGR3mU48pwNncTutmD2F98Z5A+MUSUz2dhkF94DSejiyuWmFISmIy8THkyiV/JotMdUISKtbIy5Sr3Y4c+cpiB3SY+yiaKdpGVammWZqHWW7IazE8vUEPAYUz2OS8dbexs+cYcCbA0lURNY0h03tOzSep+wrsoUVAOZ+zuoHDVawNcWrInUhYHbg8xN3o/fiCDhKy8kQFzpbIlwS5XaQibInnRtrdtIE/bMAVYsro6qU/CNJCQSTALVWqpP++wvzzaovD4Iv16AZG6sulPSIB/yU2FsZKhIDNY6m/mJipud/Y9XGNR2Xa0YBalWYrrgYeaNs9UhWxlGcTct3sdfcJ0ul2xYYSQmPJtq4jfcwm+mCYehqvBoBR70IxBFSIHbHmzlPLwIi6bBwyqT7TJBfFFAcuGGnUNb/0KvHEQz0aoHmaiNZO7b1FHvU=}
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
